# -*- coding: utf-8 -*-
"""introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QkWMFq1cQpNueI2O4Trmem0anRb_CWWY
"""

import pandas as pd
import numpy as np

"""# Introduction

## COVID data
"""

covid_data = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv")
covid_data.head(2)

covid_data[(covid_data['location']=='World')].plot(x='date', y='new_cases', title='COVID-19: Daily new cases', figsize=(9, 5))

def covid_daily(ax):
    covid_data[(covid_data['location']=='World')].plot(x='date', y='new_cases', title='COVID-19: Daily new cases', figsize=(9, 5), ax=ax)

from matplotlib import pyplot as plt

def pretty_plot(chart, save=False):
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(10, 6))

    chart(ax)
    ax.get_legend().remove()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    if save:
        fig = ax.get_figure()
        fig.savefig(f'{chart.__name__}.png')

pretty_plot(covid_daily, save=True)

"""## (Gaussian) white noise"""

white_noise_data = pd.DataFrame({'Z': np.random.normal(loc=0.0, scale=10.0, size=500)})

def white_noise(ax=None):
    white_noise_data.plot(title='Gaussian white noise', figsize=(9, 5), ax = ax)

white_noise()

white_noise_data['Z'].hist()

!pip install pingouin
import pingouin as pg

# https://pingouin-stats.org/generated/pingouin.normality.html
pg.normality(white_noise_data['Z'])

